### PR TITLE
Revert 14541fca, but remove animation, speed-up show tooltip

### LINKED ISSUE #35303: Popups on Woboq are not usable
Thanks, but there's an issue, I was able to move cursor to the link on the popup window when mouse over a variable in previous URL.
When I use this new link,  if I move cursor , the popup disappeared , so I am not able to go to the reference on the popup.

_Originally posted by @kashwy in https://github.com/ClickHouse/ClickHouse/issues/34948#issuecomment-1056091617_

### PR DESCRIPTION
**Pull request by Felixoid**
It fixes https://github.com/ClickHouse/ClickHouse/issues/35303

### CODE REVIEW

**Comment by Felixoid** [comment]
You can see how it works now on https://s3.amazonaws.com/clickhouse-test-reports/codebrowser/ClickHouse/src/Access/AccessBackup.h.html#DB::BackupPtr, I manually added the changed file there

**Comment by alexey-milovidov** [comment]
Feels somewhat slow, but normal.

**Comment by alexquuie** [comment]
i tried, it works! awesome!

**Comment by kashwy** [comment]
> 

but it's still not working for me,  which link for you?

**Comment by Felixoid** [comment]
It looks like the codebrowser image is not updated in the master yet. And the action https://github.com/ClickHouse/ClickHouse/actions/runs/4942551841/jobs/8837865562 just has put the wrong file to S3. It will be fixed reliably after https://github.com/ClickHouse/ClickHouse/pull/49701

**Pull request merged**
