### PR TITLE
Add LLVM/clang 16 support and switch to it

### PR DESCRIPTION
**Pull request by azat**
Upstream PR: https://github.com/KDAB/codebrowser/pull/110

This is a series of PRs to switch ClickHouse to LLVM 16

### CODE REVIEW

**Comment by Felixoid** [comment]
Is it possible to update upstream as well?

We have issue related to the old version of codebrowser https://github.com/ClickHouse/ClickHouse/issues/46299

**Comment by alexey-milovidov** [comment]
@Felixoid, the issue you've linked is introduced by me - I was so busy disabling the animation, round corners, shadow, and transparency, that overlooked it.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by Felixoid** [comment]
It's not clear to me if something needs to be done, or if the issue will be solved automatically.

BTW, @azat, it breaks the master. Are you sure that it actually requires minimum 16th version? https://github.com/ClickHouse/woboq_codebrowser/pull/8/files#diff-6f85a0c9e464c182bf97c7013f1eddc1738de405dc342175a15e3514ea9ef258R4

```
#0 1.645 CMake Error at generator/CMakeLists.txt:4 (Find_Package):
#0 1.645   Could not find a configuration file for package "LLVM" that is compatible
#0 1.645   with requested version "16".
#0 1.645
#0 1.645   The following configuration files were considered but not accepted:
#0 1.645
#0 1.645     /usr/lib/llvm-15/cmake/LLVMConfig.cmake, version: 15.0.7
#0 1.645     /lib/llvm-15/cmake/LLVMConfig.cmake, version: 15.0.7
#0 1.645
#0 1.645
#0 1.645
#0 1.645 -- Configuring incomplete, errors occurred!
```

Let's revert it and make it working on both versions?

**Comment by azat** [comment]
>BTW, @azat, it breaks the master. Are you sure that it actually requires minimum 16th version? [#8 (files)](https://github.com/ClickHouse/woboq_codebrowser/pull/8/files#diff-6f85a0c9e464c182bf97c7013f1eddc1738de405dc342175a15e3514ea9ef258R4)

It does not, let's simply remove that strict version requirement, I don't know why it is there - https://github.com/ClickHouse/woboq_codebrowser/pull/9

**Comment by azat** [comment]
>Is it possible to update upstream as well?

This patch is a backport of the the initial patch that is targeted upstream - https://github.com/KDAB/codebrowser/pull/110

But maybe you are talking about remove that custom ClickHouse patches, then it definitely worth it, although I don't know what was the purpose, apparently, like @alexey-milovidov wrote, some style fixes.

**Comment by alexey-milovidov** [comment]
@azat Yes, we have strict no to animations, round corners, and shadows for our website assets.

**Pull request merged**
